server:
  port: 8888
  context-path: /
  max-http-header-size: 4048576
  tomcat:
    max-http-post-size: 1000MB  #请求参数长度
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/school?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20



  # file upload max size 20M
  servlet:
        multipart:
          max-file-size: 20971520     # 文件上传大小限制为20M
          max-request-size: 20971520  # 请求大小限制为20M

  #打印sql
logging:
  level:
    com.jinfang.mapper: debug


#分页插件设置
pagehelper:
  helper-dialect: mysql
  #mapper目录
mybatis:
  mapper-locations: classpath:com/jinfang/sqlmap/*.xml
